enum ActionTypes {
  LOAD_DATA = "LOAD_DATA",
  LOAD_DATA_SUCCESS = "LOAD_DATA_SUCCESS",
  FAILURE = "FAILURE",
  INCREMENT = "INCREMENT",
  SET_TOAST_MESSAGE = "SET_TOAST_MESSAGE"
}

export default ActionTypes;
