enum ActionTypes {
  GET_APP_DATA = "GET_APP_DATA",
  GET_APP_DATA_SUCCESS = "GET_APP_DATA_SUCCESS",
  GET_APP_DATA_FAILURE = "GET_APP_DATA_FAILURE",
  SET_TOAST_MESSAGE = "SET_TOAST_MESSAGE"
}

export default ActionTypes;
