enum ActionTypes {
  GET_PROPOSALS = "GET_PROPOSALS",
  GET_PROPOSALS_SUCCESS = "GET_PROPOSALS_SUCCESS",
  GET_POLICIES = "GET_POLICIES",
  GET_POLICIES_SUCCESS = "GET_POLICIES_SUCCESS"
}

export default ActionTypes;
